server:
  port: 8095
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  security:
    enabled: false 
security:
  basic:
    enabled: false
spring:
  boot:
    admin:
      client:
        url: http://localhost:8091
        username: admin
        password: admin
  application:
    name: order-microservice
  profiles:
    active: dev
  task:    execution:      pool:        core-size: 5        max-size: 10

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order_management_db    cache:
    type: redis
    redis:
      host: localhost
      port: 6379
#   username:
#   password:

service:
  product-microservice:
    path: http://localhost:8097
  consumer-microservice:
    path: http://localhost:8094

kafka:
  bootstrapAddress: localhost:9092,localhost:9093,localhost:9094
  acks: all
  retries: 5
  retry:
    backoff:
      ms: 1000
  message:
    exchangeEventTopic:
      name: exchange-events
    productTopic:
      name: product_count_topic
    customerTopic:
      name: cust_credit_limit_topic